doctrine:
    dbal:
        dbname: '%env(resolve:DATABASE_NAME)%'
        host: '%env(resolve:DATABASE_HOST)%'
        port: '%env(resolve:DATABASE_PORT)%'
        user: '%env(resolve:DATABASE_USER)%'
        password: '%env(resolve:DATABASE_PASSWORD)%'
        driver: '%env(resolve:DATABASE_DRIVER)%'
        server_version: '%env(resolve:DATABASE_SERVER_VERSION)%'

        types:
            # Common
            datetime: App\Common\Infrastructure\Doctrine\Type\DateTimeType
            firstname: App\Common\Infrastructure\Doctrine\Type\FirstNameType
            lastname: App\Common\Infrastructure\Doctrine\Type\LastNameType
            email: App\Common\Infrastructure\Doctrine\Type\EmailType

            # Authentication
            username: App\Authentication\Infrastructure\Doctrine\Type\UsernameType
            hashed_password: App\Authentication\Infrastructure\Doctrine\Type\HashedPasswordType

            # User
            user_id: App\User\Infrastructure\Doctrine\Type\UserIdType
            user_status: App\User\Infrastructure\Doctrine\Type\UserStatusType

            # Messaging
            conversation_id: App\Messaging\Infrastructure\Doctrine\Type\ConversationIdType
            participant_id: App\Messaging\Infrastructure\Doctrine\Type\ParticipantIdType
            participant_name: App\Messaging\Infrastructure\Doctrine\Type\ParticipantNameType
            message_id: App\Messaging\Infrastructure\Doctrine\Type\MessageIdType
            message_content: App\Messaging\Infrastructure\Doctrine\Type\MessageContentType

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Authentication:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Authentication/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Authentication\Domain\Entity'

            User:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/User/Infrastructure/Doctrine/Mapping'
                prefix: 'App\User\Domain\Entity'

            Messaging:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Messaging/Infrastructure/Doctrine/Mapping'
                prefix: 'App\Messaging\Domain\Entity'
